### ISSUE TITLE
Add an Easy Way to Import the Library into Our Own Project

### ISSUE THREAD

**Issue by ObNitram** [adammyhre/Unity-Utils#5]
### Description:
 - Add the possibility to quickly integrate the library into our own project.
 - Facilitate collaboration among developers by allowing them to easily participate in the development of the library.

### Details:
- Add the option to include the library as a package from the [Unity Package Manager using a Git URL](https://docs.unity3d.com/Manual/upm-ui-giturl.html).
  - Currently impossible because there is no package manifest.
 
- Add the option to import the library as a [Git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) into our own Unity project.
  - Difficult due to the current directory structure of the library.

### Additional Notes:
I think that a decomposition into [Assembly Definitions](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html) should also be done.

**Comment by ObNitram** [comment]
I do some test and it looks like the package.json file should be in the root folder.
Some packages use another branch for installation with the package manager but I think it's more work to maintain two branches for little benefit. :thinking:

**Comment by ObNitram** [comment]
I looked at the contents of the script folder and I suggest moving the script helper to its own folder, there will probably be new helpers in the future.
Unless helpers have the principle of being at the first level of namespace to be easily usable. I don't know what to think of it. :smile:

**Comment by ObNitram** [comment]
And my proposal for decomposition into an assembly definition was more of a question.😅 It may be a little overkill to break down this library at the moment. She is still relatively small. I really don't know what the best practices and standards are with definition assemblies. Could be a good subject for a video I think.

**Comment by adammyhre** [comment]
Give it another test import.  This is probably all the changes I'll make for now until more features are added (as long as it's importing correctly)

**Comment by ObNitram** [comment]
There is no meta file. Since packages are considered immutable, Unity requires that all meta files are already generated.

### Notice
The package requires the _Core RP Library_ due to the _LoadVolumeProfile()_ extension. I believe this should be indicated in the readme.

**Comment by ObNitram** [comment]
If you want i have a pull request ready with all the meta file generated and your previous modifications.

**Comment by adammyhre** [comment]
Which meta file is missing?

**Comment by ObNitram** [comment]
Assets.meta
IEnumeratorExtensions.cs.meta
PR_GUIDELINES.md.meta
README.md.meta
package.json.meta

**Comment by ObNitram** [comment]
I tried and everything seems to work. :+1:

**Comment by adammyhre** [comment]
Alright, I'm going to merge this in.

**Comment by adammyhre** [comment]
Merged
