### ISSUE TITLE
Vector3 Extension method to convert between UnityEngine.Vector3 and System.Numerics.Vector3

### ISSUE THREAD

**Issue by PooperPig** [adammyhre/Unity-Utils#8]
Existing code that returns System.Numerics.Vector3 that are being used to populate transform.positions - and the associated code that takes a UnityEngine.Vector3 and requires a System.Numeric.Vector3

Might be a niche case, but I've found it helpful in serialisation to use System rather than Unity (it's less verbose!)

**Comment by adammyhre** [comment]
Can you elaborate and possibly give an example of the issue?  Are you proposing to add new conversion methods or a change to existing methods?

**Comment by PooperPig** [comment]
Sure. 
I am proposing a new conversion method.
The issue:
To convert between a System Vector3 and a Unity Vector3 one needs 
`newV = new System.Numerics.Vector3(oldV.X, oldV.Y. oldV.Z);`
My proposal would introduce an extension method so you can write
`newV = oldV.ToSystemVector()`

I would like input on whether 'ToSystemVector' or 'AsSystemVector' would be the preferred nomenclature.

Obviously the converse extension would be "ToUnityVector"

Because of the way Unity Vectors are structured there is a (minor) issue when serialising them as some of the calculated values are serialised (i.e. not just the x,y,z) .

Or, for example, I might read data via a non UNity package that returns data (or expects it) in System vector3s 

It's a bit of a niche thing, but I actually use it quite a lot as I import and export data to other systems.

**Comment by adammyhre** [comment]
This got me wondering if it's useful to add conversion methods for `System.Numerics.Quaternion` as well.  Anyway, I'll put this on my todo list for the weekend.

**Comment by adammyhre** [comment]
Added new classes and a few minor updates.
